### ISSUE TITLE
a little code fix, too lazy to pr

### ISSUE THREAD

**Issue by mr-m0nst3r** [BDisp/unlocker#1]
![Screenshot from 2019-10-24 15-28-55](https://user-images.githubusercontent.com/38524240/67463015-3a390c80-f673-11e9-9f4a-da34d379579a.png)

Hey there,

it's just a check to see whether the user has downloaded the package or not.
It's embarrassing that I'm downloading twice, since I wanna fix the original error with DrDonk, but saw your pull request.

It's too little code, so I'm just posting it here.

Thanks and great work.

**Comment by BDisp** [comment]
Thanks for the code. The files in the Tools folder are the iso darwin files and not the tar file which is deleted after extraction. The desired change is already made. I remind anyone that if you only need to reinstall the tools and not run the unlocker you can use the lnx-update-tools.sh files for linux or win-update-tools.cmd file for windows. Enjoy :-)

**Comment by mr-m0nst3r** [comment]
@BDisp Oh, didn't pay attention to update-tools.

Thank you and great work.
