### ISSUE TITLE
[Feature Request] Unlock for macOS Monterey

### ISSUE THREAD

**Issue by kazunetakeda25** [BDisp/unlocker#11]
New Option for macOS Monterey wanted.

**Comment by mkitchingh** [comment]
That will be up to the VMware workstation update to provide this option. There is nothing we can do until VMware has updated their libraries.

**Comment by reysantana** [comment]
Hi @mkitchingh 
Is it possible to upgrade macOS Big Sur to macOS Monetary on VMWare?

**Comment by mkitchingh** [comment]
You can try, but I wouldn't right now. Wait until the full version has been released.

**Comment by BDisp** [comment]
Thanks @mkitchingh. Tell me if is really needed to update this, which is only needed if the keys have changed or the `darwin.iso` url has been changed. For now I'm using the `VirtualBox`, which although we can't install the `Guest Additions` (so, I'm using smb and ssh for remote connections), is much more faster than `VMware`. Of course, for those who are using `ESXI` they really needed `VMware`.

**Comment by mkitchingh** [comment]
> Thanks @mkitchingh. Tell me if is really needed to update this, which is only needed if the keys have changed or the `darwin.iso` url has been changed. For now I'm using the `VirtualBox`, which although we can't install the `Guest Additions` (so, I'm using smb and ssh for remote connections), is much more faster than `VMware`. Of course, for those who are using `ESXI` they really needed `VMware`.

Thanks. I will let you know once the full release is out, or when VMware releases their update. I've never tried macOS on Virtual Box, but VMware has been working very well for me and the community I support.

**Comment by Lesliewxj** [comment]
> Hi @mkitchingh
> Is it possible to upgrade macOS Big Sur to macOS Monetary on VMWare?

Is it available for macOS Big Sur？

**Comment by BDisp** [comment]
Can someone confirm that this is working on `macOS Monterey`, please?

**Comment by xukongop** [comment]
> Hi @mkitchingh Is it possible to upgrade macOS Big Sur to macOS Monterey on VMWare?

I tried it successfully, from macOS Big Sur 11.0.1 to macOS Monetary 12.0.1


![1](https://user-images.githubusercontent.com/25893055/145164260-574b57f3-c55b-47ed-95ce-bbfc72f07477.png)

**Comment by BDisp** [comment]
Thanks for reporting this. So I'm closing as solved.
