### ISSUE TITLE
Tools not downloaded with Workstation 16.2.0 build-18760230

### ISSUE THREAD

**Issue by superbonaci** [BDisp/unlocker#15]
URL for tools has changed with `VMware® Workstation 16 Pro 16.2.0 build-18760230` on Linux. Python script need update.

**Comment by BDisp** [comment]
I'll check it. Thanks.

**Comment by moseoridev** [comment]
current url in script -> http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/core/
updated url -> http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/x86/core/

just add "x86", please.

**Comment by superbonaci** [comment]
What about `arm64` folder?

**Comment by moseoridev** [comment]
@superbonaci Can I use vmware on WOA? I guess not 😓

**Comment by BDisp** [comment]
I'll fix asap.

**Comment by shkpk** [comment]
I'm also having same problem
```
# sudo ./lnx-update-tools.sh 
Get macOS VMware Tools 3.0.3
===============================
(c) Dave Parsons 2015-18
Getting VMware Tools...
Trying to get tools from the packages folder...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/packages/com.vmware.fusion.tools.darwin.zip.tar
Tools aren't here... Be patient while I download and give a look into the core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/core/com.vmware.fusion.zip.tar
Couldn't find tools
cp: cannot stat './tools/darwin*.*': No such file or directory
```

**Comment by BDisp** [comment]
Can you please check if this was fixed with the last commit to the master branch? Thanks.

**Comment by superbonaci** [comment]
Still not working with `win-install.cmd`, File not found - darwin*.*:
````
Getting VMware Tools...
Trying to get tools from the packages folder...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/packages/com.vmware.fusion.tools.darwin.zip.tar
Tools aren't here... Be patient while I download and give a look into the core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/core/com.vmware.fusion.zip.tar
Tools aren't here... Be patient while I download and give a look into the x86.core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249//x86/core/com.vmware.fusion.zip.tar
...100%, 625 MB, 5637 KB/s, 0 seconds remainingg
Extracting com.vmware.fusion.zip.tar...
Extracting files from com.vmware.fusion.zip...
Tools from core retrieved successfully
File not found - darwin*.*
0 File(s) copied

Starting VMware services...

Finished!
````

**Comment by moseoridev** [comment]
There are two slashes in url.

**Comment by BDisp** [comment]
> There are two slashes in url.

I already fixed. Pull again, please. Thanks.

**Comment by BDisp** [comment]
> Still not working with `win-install.cmd`, File not found - darwin*.*:

I made the change by removing the slash and didn't recompile it. Maybe is the issue.

**Comment by shkpk** [comment]
> > There are two slashes in url.
> 
> I already fixed. Pull again, please. Thanks.

you fixed `core` url but not `package`

```
python gettools.py
Trying to get tools from the packages folder...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/packages/com.vmware.fusion.tools.darwin.zip.tar
Tools aren't here... Be patient while I download and give a look into the core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/core/com.vmware.fusion.zip.tar
Tools aren't here... Be patient while I download and give a look into the x86.core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.0/18760249/x86/core/com.vmware.fusion.zip.tar
...100%, 625 MB, 2829 KB/s, -1 seconds remaining
Extracting com.vmware.fusion.zip.tar...
Extracting files from com.vmware.fusion.zip...
Tools from core retrieved successfully
```

**Comment by BDisp** [comment]
> you fixed `core` url but not `package`

From `package` was on older versions only. Then was from `core` and now is from `x86/core`.

**Comment by BDisp** [comment]
@superbonaci the problem is the executable `gettools.exe` doesn't create the `tools` folder, but running `python gettools.py` the folder tools is created. I'll try to find the reason for this.

**Comment by BDisp** [comment]
> 
> 
> @superbonaci the problem is the executable `gettools.exe` doesn't create the `tools` folder, but running `python gettools.py` the folder tools is created. I'll try to find the reason for this.

Fixed.

**Comment by superbonaci** [comment]
Perfect thanks.

**Comment by OguzEkinci** [comment]
thx bro, it's working well

**Comment by meir555** [comment]
Fix:
The path of the iso in the zip file changed.
you need to edit the gettools.py file, and change the path in lines 148, 149, 153, 154
from: `.../Library/isoimages/darwin...` to `.../Library/isoimages/x86_x64/darwin...`

Then use the iso in the tools folder or copy them to C:\Program Files (x86)\VMware\VMware Workstation

**Comment by superbonaci** [comment]
@meir555 should I reopen the issue?

**Comment by BDisp** [comment]
No thanks. There is already one open #24.
