### ISSUE TITLE
Create its own backup folder for each OS

### ISSUE THREAD

**Issue by superbonaci** [BDisp/unlocker#17]
I use the same `unlocker` folder for Windows and Linux, yet they backup into same backup folder with both `lnx-install.sh` and `win-install.cmd`. Probably not a good idea. Could be possible to use separate folders for separate OSes?

**Comment by BDisp** [comment]
@superbonaci in which scenarios do you need backup folder for each OS?

- Do you use `Windows` as host and `Linux` as guest with shared folders?
- Do you use `Linux` as host and `Windows` as guest with shared folders?
- Do you use `Windows` as host and WSL with a `X11` server?
- Do you use other like remote `ssh` server?

**Comment by superbonaci** [comment]
I don't understand those questions. What I do is to unlock OSX guests under Linux and Windows using same git clone folder.

**Comment by BDisp** [comment]
> 
> 
> I don't understand those questions. What I do is to unlock OSX guests under Linux and Windows using same git clone folder.

My question is how you can access to the same git clone folder from the `OSX` guest to the both `Windows` and `Linux`.

**Comment by superbonaci** [comment]
> 
> 
> > I don't understand those questions. What I do is to unlock OSX guests under Linux and Windows using same git clone folder.
> 
> My question is how you can access to the same git clone folder from the `OSX` guest to the both `Windows` and `Linux`.

I don't access it from the guest, only from the host to run lnx-install and win-install.

**Comment by BDisp** [comment]
> I don't access it from the guest, only from the host to run lnx-install and win-install.

What OS is your host?

**Comment by superbonaci** [comment]
This is the description of the issue. Run `win-install.cmd` on Windows. It created the backup folder with these contents inside:
```
backup/
backup/x64
backup/x64/vmware-vmx-debug.exe
backup/x64/vmware-vmx.exe
backup/x64/vmware-vmx-stats.exe
backup/vmwarebase.dll
```

Then, from the same unlocker folder I run `sudo ./lnx-install.sh` on Linux, and the contents get overwritten with:
```
backup/
backup/libvmwarebase.so
backup/vmware-vmx-debug
backup/vmware-vmx-stats
backup/vmware-vmx
```
I lost my Windows files backup. This is what I mean by having separate backup directories for Windows and Linux. Could you fix this please?

**Comment by superbonaci** [comment]
thanks a lot works perfect now.
