### ISSUE TITLE
Can you check gettools.exe for 3.0.4 is flagged as virus can you verify it's ok 

### ISSUE THREAD

**Issue by gquiring** [BDisp/unlocker#21]

**Comment by BDisp** [comment]
I download again from the release version https://github.com/BDisp/unlocker/archive/refs/tags/3.0.4.zip and it not gave any virus alert on my machine. Certainly is a false positive. What anti-virus app do you use?

**Comment by gquiring** [comment]
Mine was Win 10 Microsoft scanner.  My buddy at work runs Norton and it also flagged gettools.exe.  This is the message:

Program:Win32/Uwamson.A!ml

**Comment by BDisp** [comment]
Well, I can not do anything, I can only guarantee that it has no virus. You know whether or not you risk.

**Comment by superbonaci** [comment]
Here you have the Virustotal scan results: 25/68 give positive:
https://www.virustotal.com/gui/file/9bc75a681eba79450d7d8d5eaf0221bc9ef1c7c0173861b51e41dd7f1c5b847b
Don't give it a damm, even harmless keygens are detected as positive.
