### ISSUE TITLE
Can't get Version 3.0.4 working with VMware Workstation 16.2.2 Pro

### ISSUE THREAD

**Issue by humanspida** [BDisp/unlocker#22]
Removed old VMware install, cleaned up with CCleaner and manually deleted leftover stuff I could find
Fresh install of VMware Workstation Pro 16.2.2 on Windows 10 and reboot when prompted
Made sure no VMware proceses or services were running before installing
Ran the "win-install.cmd" as Administrator and let the installer run its course
Window closes on its own after downloads and installation completes
Another reboot before running VMware Workstation or Player

No new macOS option added to Guest OS selection stage for new VM creation

Does version 3.0.4 work with VMware 16.2.2 or has it not gotten that far just yet?

Have saved the installation cmd output to a text file if thats of any use,
Everything up to "Starting VMware Services..." coz I'm just quick enough to get in before the window auto-exits

**Comment by BDisp** [comment]
Open the `cmd` as admin and copy and paste the path of the unlocker folder. Run "`win-install.cmd`" and see what is the log information. That way the cmd won't close after run. I installed the `VMware Workstation Pro 16.2.2` yesterday, after uninstall the unlocker first and I haven't any problems. `macOS` option appears after running the unlocker again.
In this issue #20 the user has successfully installed, only has network problems and I do not know why.

**Comment by humanspida** [comment]
As before:

Completely removed existing VMware install, cleaned up with CCleaner and manually deleted all leftovers
Reboot followed by a fresh install of VMware Workstation Pro 16.2.2.19200509 - reboot when prompted
Made sure no VMware proceses or services were running
Opened an Administrator CMD Prompt window and ran the "win-install.cmd" file
Let the installer run its course

Here's the result:


Microsoft Windows [Version 10.0.19044.1466]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>CD C:\Users\korba\Downloads\unlocker-3.0.4

C:\Users\korba\Downloads\unlocker-3.0.4>.\win-install.cmd

Unlocker 3.0.4 for VMware Workstation
=====================================
(c) Dave Parsons 2011-18

Set encoding parameters...
Active code page: 850

VMware is installed at: C:\Program Files (x86)\VMware\VMware Workstation\
VMware product version: 16.2.2.19200509

Stopping VMware services...

Backing up files...
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe -> C:\Users\korba\Downloads\unlocker-3.0.4\backup-windows\x64\vmware-vmx.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe -> C:\Users\korba\Downloads\unlocker-3.0.4\backup-windows\x64\vmware-vmx-debug.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe -> C:\Users\korba\Downloads\unlocker-3.0.4\backup-windows\x64\vmware-vmx-stats.exe
1 File(s) copied
C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll -> C:\Users\korba\Downloads\unlocker-3.0.4\backup-windows\vmwarebase.dll
1 File(s) copied

Patching...
Traceback (most recent call last):
  File "unlocker.py", line 401, in <module>
    main()
  File "unlocker.py", line 391, in main
    patchsmc(vmx, vmx_so)
  File "unlocker.py", line 230, in patchsmc
    with open(name, 'r+b') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\VMware\\VMware Workstation\\x64\\vmware-vmx.exe'
[9060] Failed to execute script 'unlocker' due to unhandled exception!

Getting VMware Tools...
Trying to get tools from the packages folder...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.1/18811640/packages/com.vmware.fusion.tools.darwin.zip.tar
Tools aren't here... Be patient while I download and give a look into the core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.1/18811640/core/com.vmware.fusion.zip.tar
Tools aren't here... Be patient while I download and give a look into the x86.core.vmware.fusion.tar file
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.1/18811640/x86/core/com.vmware.fusion.zip.tar
...100%, 625 MB, 6064 KB/s, 0 seconds remaining
Extracting com.vmware.fusion.zip.tar...
Extracting files from com.vmware.fusion.zip...
Tools from core retrieved successfully
File not found - darwin*.*
0 File(s) copied

Starting VMware services...

Finished!



So, it recognises VMware is installed and it looks like certain files are backed up but the patching fails after that with a file not found error, followed by failing to execute script due to an unhandled exception

It then continues to download the tools anyway but then throws another file not found error when it goes looking for darwin

I see there's double backslashes between folder names in the first file not found error details, is that significant?

Unfortunately I don't know what to do with this information : )

**Comment by BDisp** [comment]
I don't know why you need to use the CCleaner. Sometimes it breaks something. I uninstalled all again, deletes the C:\Program Files (x86)\VMware\ folder. Reinstall again, run the unlocker without any errors. Did you download from this link https://github.com/BDisp/unlocker/archive/refs/tags/3.0.4.zip


> I see there's double backslashes between folder names in the first file not found error details, is that significant?

That are escape char, there is no problem with the app. It's something on your system that don't let the `VMware` being installed in the right way.

**Comment by humanspida** [comment]
OK, this morning I reinstalled VMware Workstation 16.2.2 - there is no problem with the install as far as I can tell.
It's a standard Windows software installer - launch and follow prompts, use defaults, finished, reboot.
Everything works as you would expect, able to load .iso image files for VMs, both live and installed to disk
I'm certain there's no problem with my VMware installation at this point...

What did suddenly come back to mind this morning was my firewall / antivirus / containment setup
So, I had a look at the containment logs and found it'd been containing the installer / unintaller on the sly
Changed things so the install and uninstall files wouldn't be contained and killed all the running VMware stuff
Ran the win-install.cmd again and the output didn't spit any errors or complain at me about anything this time
Window closes automatically as it should
Opened VMware Workstation again...

SUCCESS

I always forget about my security stuff, it does it's job so well it's almost like its not there sometimes

Thanks very much for responding so quick and being patient with my late night lapse and idiocy
Also, thanks for keeping the unlocker alive : )

**Comment by BDisp** [comment]
Some users are complaining about virus alert (https://github.com/BDisp/unlocker/issues/21), but are false positive. If firewall/antivirus work silent the user will not be alerted about that and the patch will fail. If it's fixed please close this issue.
