### ISSUE TITLE
ISO path in vmtools has changed

### ISSUE THREAD

**Issue by meir555** [BDisp/unlocker#24]
The ISO for the current version is in:
`payload/VMware Fusion.app/Contents/Library/isoimages/x86_x64/darwin.iso`
and not in:
`payload/VMware Fusion.app/Contents/Library/isoimages/darwin.iso`

The `gettools.py` file needs to be updated in lines 148-149, 153-154
Or, even better, check if there is a file in the current path, and if not check the `/x86_x64/` subfolder.

Another suggestion, in the `win-install.cmd`, copy the iso files to `C:\Program Files (x86)\VMware\VMware Workstation\` after `gettools.py` is done.

**Comment by BDisp** [comment]
> Another suggestion, in the `win-install.cmd`, copy the iso files to `C:\Program Files (x86)\VMware\VMware Workstation\` after `gettools.py` is done.

The `win-install.cmd` already copy by using the `%InstalPath%` information. If you are also using others versions then you must do the copy yourself.

**Comment by meir555** [comment]
> > Another suggestion, in the `win-install.cmd`, copy the iso files to `C:\Program Files (x86)\VMware\VMware Workstation\` after `gettools.py` is done.
> 
> The `win-install.cmd` already copy by using the `%InstalPath%` information. If you are also using others versions then you must do the copy yourself.

Thanks, so maybe change the default to overwrite darwin.iso if exist?

**Comment by BDisp** [comment]
> Thanks, so maybe change the default to overwrite darwin.iso if exist?

But it already overwrite the exist one if you download the tools again. See the `README` file to see the different about `win-install.cmd`, `win-uninstall.cmd` and `win-update-tools.cmd`.

**Comment by heapxor** [comment]
hi,
dont get that thread... i dont have that path 
payload/VMware Fusion.app/Contents/Library/isoimages/x86_x64/darwin.iso
only without x86_x64

also there are no mentioned files > win-install.cmd, win-uninstall.cmd and win-update-tools.cmd.

i run vmware player pro on win11... is there some fix / or how to get the tools and install them?

also there is darwin15.iso ...no clue whats that one.


thanks

**Comment by BDisp** [comment]
> hi,
> dont get that thread... i dont have that path
> payload/VMware Fusion.app/Contents/Library/isoimages/x86_x64/darwin.iso

Hi. This is the new path where the `darwin.iso` and `darwinPre15.iso` reside inside the zip file.

> only without x86_x64

Perhaps you are using the same zip file downloaded early. If you install the new release https://github.com/BDisp/unlocker/releases/tag/3.0.5 you will see the path was changed in the zip file.

> also there are no mentioned files > win-install.cmd, win-uninstall.cmd and win-update-tools.cmd.

See the [README](https://github.com/BDisp/unlocker/blob/master/README.md) where are all explained.

> i run vmware player pro on win11... is there some fix / or how to get the tools and install them?

Get the latest release [here](https://github.com/BDisp/unlocker/releases/latest).

> also there is darwin15.iso ...no clue whats that one.
>
> thanks

It's `darwinPre15.iso`. Is for MAC OS X  prior versions. See the explanation [here](https://docs.vmware.com/en/VMware-Tools/12.1.0/com.vmware.vsphere.vmwaretools.doc/GUID-D8892B15-73A5-4FCE-AB7D-56C2C90BD951.html):

`VMware Tools installer from darwinPre15.iso does not proceed with installation on MAC OS X guest operating systems versions 10.11 or later. `

You welcome.

**Comment by heapxor** [comment]
@BDisp hello,
maybe i am confusing something... i installed -> https://github.com/paolo-projects/auto-unlocker/

i extracted darwin.iso from http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.4/20071091/x86/core/com.vmware.fusion.zip.tar

but maybe http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.5/20904517/x86/core/ here is the latest?

Still inside macos display settings are not working properly... see screenshots from osx native; osx in vmware (second photo)
https://imgur.com/a/VTlPY7N
ie there is no possibility to increase text size...;/

thanks!

**Comment by BDisp** [comment]
> but maybe http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.5/20904517/x86/core/ here is the latest?

No, the latest is http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/13.0.0/20802013/arm64/core/com.vmware.fusion.zip.tar


> Still inside macos display settings are not working properly... see screenshots from osx native; osx in vmware (second photo)
> https://imgur.com/a/VTlPY7N
> ie there is no possibility to increase text size...;/

There is no way to have a really osx on a virtual machine, of course.

**Comment by heapxor** [comment]
i assume you meant http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/13.0.0/20802013/x86/core/


hm so this is common bug/issue? in that case its not usable ... as OS

**Comment by heapxor** [comment]
okay installed latest 13x tools , still same issue with the display... unknow - font is small... 
bit confused whats the purpose to run such broken macos in vmware...

**Comment by BDisp** [comment]
Did you already added `smc.version = "0"` to the VMX file? The issue you are dealing has not to do with the `unlocker` repo, which download the darwin tools and unlock the macOS dropdown list to allow create a OS X virtual machine. You have to google search about your issue.

**Comment by heapxor** [comment]
@BDisp sure, that was added. i understand your concern.
i thought that people here also have some experience of running macos using that unlocker...

**Comment by BDisp** [comment]
No problem. If somebody that had the same problem probably could help you.

**Comment by heapxor** [comment]
> > but maybe http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.5/20904517/x86/core/ here is the latest?
> 
> No, the latest is http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/13.0.0/20802013/arm64/core/com.vmware.fusion.zip.tar
> 
> > Still inside macos display settings are not working properly... see screenshots from osx native; osx in vmware (second photo)
> > https://imgur.com/a/VTlPY7N
> > ie there is no possibility to increase text size...;/
> 
> There is no way to have a really osx on a virtual machine, of course.

so seems noeone here?:( any idea where to report such an issue?
