### ISSUE TITLE
[Fedora 37] Script stuck 

### ISSUE THREAD

**Issue by ghost** [BDisp/unlocker#27]
I have VMWare Workstation Pro 17 (activated) installed on Fedora 37 Workstation.

It is stuck at:

Getting VMware Tools...
Trying to get tools from the packages folder...

I don't know what to do!
I've tried other forks, but they are getting stuck also.
I'm using the 3.0.5 version.

**Comment by BDisp** [comment]
What the is `python` version? Can you manually download the tools?

**Comment by ghost** [comment]
Well, I'm using python 3.11.1, and the downloaded fusion should be 13.0.0 right?
also, it should be placed in the tools directory?

**Comment by BDisp** [comment]
Yes.

**Comment by ghost** [comment]
I ran it again, it asked me if I wanna redownload fusion, and I said no.
Afterwards, it printed `Finished.` and closed.
I ran `lnx-update-tools.sh` afterwards and It also said `Finished.` at the end.
Is it working now?
I see the macOS entry in VMWare.

**Comment by BDisp** [comment]
> Is it working now?
> I see the macOS entry in VMWare.

Yes. If you are seeing macOS entry in VMWare then all is working as it should. I think the download was locked at beginning for some reason, like so net signal, etc...
If you still having problems with this please reopen this issue.
