### ISSUE TITLE
Not working for Shared VMs?

### ISSUE THREAD

**Issue by tempelmann** [BDisp/unlocker#3]
(Sorry to open this ticket here - but DrDonk doesn't seem to want tickets, and you seem to be more on top of it, currently)

I have successfully used unlocker to run my 10.13 based VM (created with Fusion) on Workstation Pro 10.15.1. However, when I then try to turn it into a Shared VMs, using the cloning option, the macOS support options disappeared and I cannot boot the VM any more.

Is this a known issue or a bug? Can this be fixed somehow?

**Comment by BDisp** [comment]
Actually on Shared VMs the macOS options are blocked but if you want to share you should use Manage->Share and not Clone. However, I recommend that if you happen to want to stop sharing with Manage->Stop Sharing you should be careful to check first if the VM is not being used, as you risk being blocked. In that case I advise to always have a copy of the vmx file if there are problems with permissions.

**Comment by tempelmann** [comment]
I also tried to share with Move instead of Clone. Same result: The macOS options vanish, and it doesn't boot any more because the UEFI boot can't load the macOS any more, I think.

I want to use the share feature so that the macOS VM runs always, without me needing to start the GUI and the Workstation app - I want the macOS VM to start automatically when I reboot Linux, even if I do not login. Is there another way to do that?

**Comment by BDisp** [comment]
You will excuse me but you will have to google it about this as there must be many options to that effect.

**Comment by tempelmann** [comment]
Alright. Thanks for your help
