### ISSUE TITLE
the tools needs an update

### ISSUE THREAD

**Issue by mhmd2234** [BDisp/unlocker#32]
im still getting this error Getting VMware Tools...
Trying to get tools from the packages folder...
Couldn't find tools
Fichier introuvable - darwin*.*
0 fichier(s) copié(s)
Finished!

**Comment by BDisp** [comment]
Impossible. I run `.\win-update-tools.cmd` without any error. You are on `Windows` or `Linux`? Did you download the last release from here https://github.com/BDisp/unlocker/releases/tag/3.0.6.

**Comment by mhmd2234** [comment]
yes on windows + downloaded it

**Comment by BDisp** [comment]
Do you are running as admin?

**Comment by mhmd2234** [comment]
yep

**Comment by BDisp** [comment]
I thought you have this issue fixed. Can you download from the follow link?
 https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/13.0.1/21139760/universal/core/com.vmware.fusion.zip.tar

If you can, then you mustn't having any problem to run the command to get the tools. I see you have a French language installed. May be someone who have the same layout as your can help you.

**Comment by mhmd2234** [comment]
yea i can but the tool cant download it not sure what is the proplem

**Comment by BDisp** [comment]
Sorry but I don't know why you are having this issue. I ask if someone else is having the same issue, please say it here. Thanks.

**Comment by Scylune** [comment]
Hey :)

@BDisp 
I've just... removed an unlocker (maybe Paolo's) from my working 17.0.2 workstation just to try yours XD
After removing it I've checked that I couldn't add another AppleOS VM.
It was the 1st time I've downloaded it btw. It works fine (well, like the previous I was using) 
AppleOS is back, and, like that other unlocker offers choices for mac OS 13 and even 14.
Windows 11 22h2 French + Vmware Workstation 17.0.2.

@mhmd2234 
Sorry it works on mine...


My output. The only thing I add everytime is 'pause' at the end of the batch.

```
Unlocker 3.0.4 for VMware Workstation
=====================================
(c) Dave Parsons 2011-18

Set encoding parameters...
Page de codes active : 850

VMware is installed at: C:\Program Files (x86)\VMware\VMware Workstation\
VMware product version: 17.0.2.21581411

Stopping VMware services...

Backing up files...
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe -> E:\Logiciels\VMware\17.0.0\Archive Unlockers\Par BDisp\unlocker-3.0.6 2023-02-06\unlocker-3.0.6\backup-windows\x64\vmware-vmx.exe
1 fichier(s) copié(s)
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe -> E:\Logiciels\VMware\17.0.0\Archive Unlockers\Par BDisp\unlocker-3.0.6 2023-02-06\unlocker-3.0.6\backup-windows\x64\vmware-vmx-debug.exe
1 fichier(s) copié(s)
C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe -> E:\Logiciels\VMware\17.0.0\Archive Unlockers\Par BDisp\unlocker-3.0.6 2023-02-06\unlocker-3.0.6\backup-windows\x64\vmware-vmx-stats.exe
1 fichier(s) copié(s)
C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll -> E:\Logiciels\VMware\17.0.0\Archive Unlockers\Par BDisp\unlocker-3.0.6 2023-02-06\unlocker-3.0.6\backup-windows\vmwarebase.dll
1 fichier(s) copié(s)

Patching...
File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xcd6300
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xcd6320
(...)

File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xf98e10
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xf98e30
(...)

File: C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xd32a30
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xd32a50
(...)

GOS Patching: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
GOS Patched flag @: 0x4e85c0
(...)
GOS Patched flag @: 0x59e5c0
GOS Patched: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll

Getting VMware Tools...
Trying to get tools from the packages folder...
Retrieving Darwin tools from: https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/13.0.2/21581413/universal/core/com.vmware.fusion.zip.tar
...100%, 676 MB, 10361 KB/s, 0 seconds remaining
Extracting com.vmware.fusion.zip.tar...
Extracting files from com.vmware.fusion.zip...
Tools from core retrieved successfully
E:\Logiciels\VMware\17.0.0\Archive Unlockers\Par BDisp\unlocker-3.0.6 2023-02-06\unlocker-3.0.6\tools\darwin.iso -> C:\Program Files (x86)\VMware\VMware Workstation\darwin.iso
E:\Logiciels\VMware\17.0.0\Archive Unlockers\Par BDisp\unlocker-3.0.6 2023-02-06\unlocker-3.0.6\tools\darwinPre15.iso -> C:\Program Files (x86)\VMware\VMware Workstation\darwinPre15.iso
2 fichier(s) copié(s)

Starting VMware services...

Finished!
Appuyez sur une touche pour continuer...
```

**Comment by BDisp** [comment]
@Scylune thank you very much for the confirmation that this works on a French language OS. 

> My output. The only thing I add everytime is 'pause' at the end of the batch.
>
Maybe you are running directly from the explorer.exe which will closed after finished. Normally we open on a terminal and run from there where you will see all the log operation and will not close.

@mhmd2234 do you already fixed it? I remember that installing on a already unlocked will corrupt it. If this is the case uninstall VMWare and reinstall.
