### ISSUE TITLE
VMware updated to 17.6.2 - boot-loop returns..

### ISSUE THREAD

**Issue by ayles2014** [BDisp/unlocker#42]
The latest version of VMware/Linux - 17.6.2 - seems to have broken unlockers.. 17.6.1 worked OK... but with 17.6.2 the boot-loop has resurfaced..

**Comment by BDisp** [comment]
Did you've done a VMware/Linux fresh install? Don't forget that when `unlocker` is already been applied when upgrading to a new VMware version it's necessary to run first the `lnx-uninstall.sh` to replace the original files and after the upgrade run the `lnx-install.sh` again. I installed the VMware/Linux - 17.6.2 and applied the `unlocker` without any issue. Can you be more specific please?

![image](https://github.com/user-attachments/assets/c0178379-932f-48b9-961d-6bba01cad70c)

![image](https://github.com/user-attachments/assets/08ea82de-9506-44f6-8d63-53c12200e55c)

**Comment by ayles2014** [comment]
Thanks for confirming that it _should_ be OK with 17.6.2..     I have set up another installation on a different system, and can confirm that it does work correctly (Fedora 41, kernel 6.12.6) , so the problem is with my (older..) system.

**Comment by BDisp** [comment]
Glad you fixed your issue. Closing this issue as not related with `unlocker`.
