### ISSUE TITLE
Error on vmware workstation 16 pro

### ISSUE THREAD

**Issue by yuritry** [BDisp/unlocker#6]
GOS Patching: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
Traceback (most recent call last):
  File "unlocker.py", line 401, in <module>
    main()
  File "unlocker.py", line 397, in main
    patchbase(vmwarebase)
  File "unlocker.py", line 306, in patchbase
    f = open(name, 'r+b')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmwarebase.dll'
[5148] Failed to execute script unlocker

**Comment by mkitchingh** [comment]
It works fine on VMware 16. 
One of these is likely the issue:
1) You didn't run it as administrator.
2) VMware was open. 
3) VMware service were running and need to be stopped.

**Comment by BDisp** [comment]
@yuritry, @mkitchingh is right.

**Comment by BDisp** [comment]
`Workstation 16 Pro` working fine. So I will close.
