### ISSUE TITLE
AMD Ryzen Error

### ISSUE THREAD

**Issue by e-cl** [BDisp/unlocker#8]
Hello.
I'm trying to install Catalina in VMWare virtual machine, but after starting it i get the error message "he CPU has been disabled by the guest operating system. Power off or reset the virtual machine". I suppose that is because my host is based on AMD Ryzen CPU. Is there any chance i can overcome this issue?
Please, any help much appreciated.

**Comment by BDisp** [comment]
See this:
https://appuals.com/fix-the-cpu-has-been-disabled-by-the-guest-operating-system/
and this:
https://kb.vmware.com/s/article/2000542

That never happened to me.

**Comment by e-cl** [comment]
Thank you for response.
Ye, i've seen that, but after altering vmx ile with cpuid VMWare  says "This virtual machine requires AVX2 but AVX is not present. The virtual machine cannot be poweres on."
My laptop has AMD Ryzen 5 2500u CPU if that's the reason.

**Comment by BDisp** [comment]
Sorry. I am not aware of these limitations and you will have to try to find a solution on your own. Unless someone else who read this issue could give you an answer.

**Comment by NaNonnI** [comment]
Yup same thing with Amd Ryzen 9 3900x

**Comment by BDisp** [comment]
With Amd Ryzen I can't help. That why I only buy intel :-)

**Comment by NaNonnI** [comment]
> With Amd Ryzen I can't help. That why I only buy intel :-)

Intel is SOOOOOOO expensive x)

**Comment by ghost** [comment]
AMD Ryzen 4000 series. 8 core. Same issue, it's worth a google.

**Comment by xchwarze** [comment]
Tested OK with Ryzen 9 3900x and 5900x
Steps are in this manual https://xchwarze.medium.com/como-instalar-macos-en-vmware-y-no-morir-en-el-intento-592747c543d0

**Comment by BDisp** [comment]
Thank you for sharing. I would like to know if those having this issue if these information provided fixes it, please.

**Comment by BDisp** [comment]
No feedback received so I'm closing.
