### ISSUE TITLE
Started with Administrator Privileges BUT...

### ISSUE THREAD

**Issue by NaNonnI** [BDisp/unlocker#9]
GOS Patching: C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
Traceback (most recent call last):
  File "unlocker.py", line 401, in <module>
    main()
  File "unlocker.py", line 397, in main
    patchbase(vmwarebase)
  File "unlocker.py", line 306, in patchbase
    f = open(name, 'r+b')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmwarebase.dll'
[4088] Failed to execute script unlocker

**Comment by BDisp** [comment]
Are you running as administrator?

**Comment by NaNonnI** [comment]
> Are you running as administrator?

"Started with Administrator Privileges"

**Comment by mkitchingh** [comment]
Did you close out VMware before running it?

**Comment by NaNonnI** [comment]
> Did you close out VMware before running it?

Yup

**Comment by NaNonnI** [comment]
> Did you close out VMware before running it?

Oh, it's work, looks like the "stop service" things don't work LOL.
I have to go with Process Hacker to stop all things

**Comment by NaNonnI** [comment]
Oh and xcopy don't work at all

**Comment by mkitchingh** [comment]
If those commands aren't working, sounds like something might be wrong with your PC.

**Comment by BDisp** [comment]
Sorry, I didn't read the title. It looks like you have another VMware dependent service still attached. Have you try to restart and run again?

**Comment by NaNonnI** [comment]
> Sorry, I didn't read the title. It looks like you have another VMware dependent service still attached. Have you try to restart and run again?

I see that vmware has a lot of other .exe running in the background (sorry for my english)

So I recommand you to replace the stop services by

echo.
echo Stopping VMware services...
net stop vmware-view-usbd > NUL 2>&1
net stop VMwareHostd > NUL 2>&1
net stop VMAuthdService > NUL 2>&1
net stop VMUSBArbService > NUL 2>&1
taskkill /F /IM vmware.exe > NUL 2>&1
taskkill /F /IM vmware-tray.exe > NUL 2>&1
taskkill /F /IM vmware-authd.exe > NUL 2>&1
taskkill /F /IM vmware-hostd.exe > NUL 2>&1
taskkill /F /IM vmware-usbarbitrator64.exe > NUL 2>&1

**Comment by BDisp** [comment]
Did you already try theses commands? Normally after install VMware and before first time running, it's recommended to run unlocker.

**Comment by NaNonnI** [comment]
> Did you already try theses commands? Normally after install VMware and before first time running, it's recommended to run unlocker.

Well my VMware was already installed and configured so.. x)

**Comment by BDisp** [comment]
If anyones else thinks it's better to add these commands, please give feedback. Thanks.

**Comment by mkitchingh** [comment]
I do not. I've probably run unlocker over 100 times with VMware already installed. I've never run into this and don't know anyone else who has either.

**Comment by BDisp** [comment]
I already faced these into this little issues, but nothing that a kill task don't fix :-)

**Comment by martianatwork** [comment]
@BDisp killing the services before starting the other process it a better idea, it will just save some time.

**Comment by razvanmarcus** [comment]
Looks like you are executing unlocker.exe instead of win-install.bat
